site_name: My Docs
nav:
  - Home: index.md
  - Hogehoge: hogehoge.md
  - ほげ: hoge.md
  - 数式: formula.md
theme: 
  name: readthedocs
  language: 'ja'
extra:
  search:
    language: 'ja'
markdown_extensions:
  - pymdownx.arithmatex
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
